Resources:
  RouletteDynamoDbTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${self:provider.environment.ROULETTE_TABLE}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST
  BetDynamoDbTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${self:provider.environment.BET_TABLE}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: 'S'
        - AttributeName: rouletteId
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
      GlobalSecondaryIndexes:
        - IndexName: rouletteIdIndex
          KeySchema:
            - AttributeName: rouletteId
              KeyType: HASH
          Projection:
            ProjectionType: 'ALL'
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      BillingMode: PAY_PER_REQUEST
  UserTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${self:provider.environment.USER_TABLE}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: 'S'
        - AttributeName: city
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
        - AttributeName: 'city'
          KeyType: 'RANGE'
      BillingMode: PAY_PER_REQUEST
